name: Plugin Feature Request
description: Create a feature request for one of my existing plugins, to request new plugins please go to Aliucord/plugin-requests.
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Time to get creative!
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required.
      placeholder: username#0000
    validations:
      required: false
  - type: dropdown
    id: plugin-choose
    attributes:
      label: Which Plugin?
      description: Choose what plugin you are making a feature request for.
      multiple: false
      options:
        - label: SilentTyping
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: What is it that you'd like to see?
      description: Also, you'd like to, give me a bit more information on what you'd like this plugin to do and/or how you want it to work.
      placeholder: I think ... would be a cool feature to add, also if it could do ... too? This would be awesome, thanks!
    validations:
      required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Did you check to make sure your feature has not already been requested?
      options:
        - label: I did indeed check to make sure my feature request is original!
          required: true